/* For license and copyright information please see LEGAL file in repository */

// https://en.wikipedia.org/wiki/ISO_3166-1
// https://nuget.pkg.github.com/annexare/Countries/blob/master/data/countries.json
export const Regions = [
    {
        englishName: "Afghanistan",
        nativeName: "افغانستان",
        phone: "93",
        iso3166_1_a2: "AF",
        iso3166_1_a3: "AFG",
        iso3166_1_num: "004",
        continent: "AS",
        capital: "Kabul",
        currency: "AFN",
        languages: ["ps", "uz", "tk"]
    }, {
        englishName: "Australia",
        nativeName: "Australia",
        phone: "61",
        iso3166_1_a2: "AU",
        iso3166_1_a3: "AUS",
        iso3166_1_num: "036",
        continent: "OC",
        capital: "Canberra",
        currency: "AUD",
        languages: ["en"]
    }, {
        englishName: "Azerbaijan",
        nativeName: "Azərbaycan",
        phone: "994",
        iso3166_1_a2: "AZ",
        iso3166_1_a3: "AZE",
        iso3166_1_num: "031",
        continent: "AS",
        capital: "Baku",
        currency: "AZN",
        languages: ["az"]
    }, {
        englishName: "Bahrain",
        nativeName: "‏البحرين",
        phone: "973",
        iso3166_1_a2: "BH",
        iso3166_1_a3: "BHR",
        iso3166_1_num: "048",
        continent: "AS",
        capital: "Manama",
        currency: "BHD",
        languages: ["ar"]
    }, {
        englishName: "Canada",
        nativeName: "Canada",
        phone: "1",
        iso3166_1_a2: "CA",
        iso3166_1_a3: "CAN",
        iso3166_1_num: "124",
        continent: "NA",
        capital: "Ottawa",
        currency: "CAD",
        languages: ["en", "fr"]
    }, {
        englishName: "China",
        nativeName: "中国",
        phone: "86",
        iso3166_1_a2: "CN",
        iso3166_1_a3: "CHN",
        iso3166_1_num: "156",
        continent: "AS",
        capital: "Beijing",
        currency: "CNY",
        languages: ["zh"]
    }, {
        englishName: "Denmark",
        nativeName: "Danmark",
        phone: "45",
        iso3166_1_a2: "DK",
        iso3166_1_a3: "DNK",
        iso3166_1_num: "208",
        continent: "EU",
        capital: "Copenhagen",
        currency: "DKK",
        languages: ["da"]
    }, {
        englishName: "Egypt",
        nativeName: "مصر‎",
        phone: "20",
        iso3166_1_a2: "EG",
        iso3166_1_a3: "EGY",
        iso3166_1_num: "818",
        continent: "AF",
        capital: "Cairo",
        currency: "EGP",
        languages: ["ar"]
    }, {
        englishName: "Finland",
        nativeName: "Suomi",
        phone: "358",
        iso3166_1_a2: "FI",
        iso3166_1_a3: "FIN",
        iso3166_1_num: "246",
        continent: "EU",
        capital: "Helsinki",
        currency: "EUR",
        languages: ["fi", "sv"]
    }, {
        englishName: "France",
        nativeName: "France",
        phone: "33",
        iso3166_1_a2: "FR",
        iso3166_1_a3: "FRA",
        iso3166_1_num: "250",
        continent: "EU",
        capital: "Paris",
        currency: "EUR",
        languages: ["fr"]
    }, {
        englishName: "Germany",
        nativeName: "Deutschland",
        phone: "49",
        iso3166_1_a2: "DE",
        iso3166_1_a3: "DEU",
        iso3166_1_num: "276",
        continent: "EU",
        capital: "Berlin",
        currency: "EUR",
        languages: ["de"]
    }, {
        englishName: "Hong Kong",
        nativeName: "香港",
        phone: "852",
        iso3166_1_a2: "HK",
        iso3166_1_a3: "HKG",
        iso3166_1_num: "344",
        continent: "AS",
        capital: "City of Victoria",
        currency: "HKD",
        languages: ["zh", "en"]
    }, {
        englishName: "India",
        nativeName: "भारत",
        phone: "91",
        iso3166_1_a2: "IN",
        iso3166_1_a3: "IND",
        iso3166_1_num: "356",
        continent: "AS",
        capital: "New Delhi",
        currency: "INR",
        languages: ["hi", "en"]
    }, {
        englishName: "Iraq",
        nativeName: "العراق",
        phone: "964",
        iso3166_1_a2: "IQ",
        iso3166_1_a3: "IRQ",
        iso3166_1_num: "368",
        continent: "AS",
        capital: "Baghdad",
        currency: "IQD",
        languages: ["ar", "ku"]
    }, {
        englishName: "Jordan",
        nativeName: "الأردن",
        phone: "962",
        iso3166_1_a2: "JO",
        iso3166_1_a3: "JOR",
        iso3166_1_num: "400",
        continent: "AS",
        capital: "Amman",
        currency: "JOD",
        languages: ["ar"]
    }, {
        englishName: "Kuwait",
        nativeName: "الكويت",
        phone: "965",
        iso3166_1_a2: "KW",
        iso3166_1_a3: "JKWT",
        iso3166_1_num: "414",
        continent: "AS",
        capital: "Kuwait City",
        currency: "KWD",
        languages: ["ar"]
    }, {
        englishName: "Lebanon",
        nativeName: "لبنان",
        phone: "961",
        iso3166_1_a2: "LB",
        iso3166_1_a3: "LBN",
        iso3166_1_num: "422",
        continent: "AS",
        capital: "Beirut",
        currency: "LBP",
        languages: ["ar", "fr"]
    }, {
        englishName: "Oman",
        nativeName: "عمان",
        phone: "968",
        iso3166_1_a2: "OM",
        iso3166_1_a3: "OMN",
        iso3166_1_num: "512",
        continent: "AS",
        capital: "Muscat",
        currency: "OMR",
        languages: ["ar"]
    }, {
        englishName: "Pakistan",
        nativeName: "Pakistan",
        phone: "92",
        iso3166_1_a2: "PK",
        iso3166_1_a3: "PAK",
        iso3166_1_num: "586",
        continent: "AS",
        capital: "Islamabad",
        currency: "PKR",
        languages: ["en", "ur"]
    }, {
        englishName: "Persia",
        nativeName: "ایران",
        iso3166_1_a2: "IR",
        iso3166_1_a3: "IRN",
        iso3166_1_num: "364",
        phone: "98",
        continent: "AS",
        capital: "Tehran",
        currency: "IRR",
        languages: ["fa"]
    }, {
        englishName: "Qatar",
        nativeName: "قطر",
        phone: "974",
        iso3166_1_a2: "QA",
        iso3166_1_a3: "QAT",
        iso3166_1_num: "634",
        continent: "AS",
        capital: "Doha",
        currency: "QAR",
        languages: ["ar"]
    }, {
        englishName: "Russia",
        nativeName: "Россия",
        phone: "7",
        iso3166_1_a2: "RU",
        iso3166_1_a3: "RUS",
        iso3166_1_num: "643",
        continent: "EU",
        capital: "Moscow",
        currency: "RUB",
        languages: ["ru"]
    }, {
        englishName: "Saudi Arabia",
        nativeName: "العربية السعودية",
        phone: "966",
        iso3166_1_a2: "SA",
        iso3166_1_a3: "SAU",
        iso3166_1_num: "682",
        continent: "AS",
        capital: "Riyadh",
        currency: "SAR",
        languages: ["ar"]
    }, {
        englishName: "Turkey",
        nativeName: "Türkiye",
        phone: "90",
        iso3166_1_a2: "TR",
        iso3166_1_a3: "TUR",
        iso3166_1_num: "792",
        continent: "AS",
        capital: "Ankara",
        currency: "TRY",
        languages: ["tr"]
    }, {
        englishName: "United Arab Emirates",
        nativeName: "دولة الإمارات العربية المتحدة",
        iso3166_1_a2: "AE",
        iso3166_1_a3: "ARE",
        iso3166_1_num: "784",
        phone: "971",
        continent: "AS",
        capital: "Abu Dhabi",
        currency: "AED",
        languages: ["ar"]
    }, {
        englishName: "United Kingdom",
        nativeName: "United Kingdom",
        iso3166_1_a2: "GB",
        iso3166_1_a3: "GBR",
        iso3166_1_num: "826",
        phone: "44",
        continent: "EU",
        capital: "London",
        currency: "GBP",
        languages: ["en"]
    }, {
        englishName: "United States",
        nativeName: "United States",
        iso3166_1_a2: "IR",
        iso3166_1_a3: "IRN",
        iso3166_1_num: "364",
        phone: "1",
        continent: "NA",
        capital: "Washington D.C.",
        currency: "USD,USN,USS",
        languages: ["en"]
    },
]
